power_consumption<- read.csv("household_power_consumption.txt", header=TRUE,sep=";",nrows = 2075259,check.names = FALSE,stringsAsFactors = FALSE,comment.char = " ",quote = '\"')
power_data<-subset(power_consumption,Date %in% c("1/2/2007","2/2/2007"))
power_data$Date<- as.Date(power_data$Date,format = "%d/%m/%Y")
datetime<- paste((as.Date(power_data$Date)), power_data$Time)
datetime<-as.POSIXct(datetime)
Active_power<-as.numeric(power_data$Global_active_power)
png("plot2.png", width = 480, height = 480)
plot(datetime,Active_power, type = "l",ylab = "GLobal Active Power (kW)")
dev.off()