power_consumption<- read.csv("household_power_consumption.txt", header=TRUE,sep=";",nrows = 2075259,check.names = FALSE,stringsAsFactors = FALSE,comment.char = " ",quote = '\"')
power_data<-subset(power_consumption,Date %in% c("1/2/2007","2/2/2007"))
power_data$Date<- as.Date(power_data$Date,format = "%d/%m/%Y")
datetime<- paste((as.Date(power_data$Date)), power_data$Time)
datetime<-as.POSIXct(datetime)
sub_metering_1<-as.numeric(power_data$Sub_metering_1)
sub_metering_2<-as.numeric(power_data$Sub_metering_2)
sub_metering_3<-as.numeric(power_data$Sub_metering_3)
png("plot3.png", width = 480, height = 480)
plot(datetime,sub_metering_1,type="l", ylab="Energy Submetering", xlab="")
lines(datetime, sub_metering_2, type="l", col="red")
lines(datetime, sub_metering_3, type="l", col="blue")
legend("topright",c("Sub_metering_1", "Sub_metering_2", "Sub_metering_3"),lty=1, lwd=2.5, col=c("black", "red", "blue"))
dev.off()